from django.urls import path
from main.views import (
    show_main,
    login,
    register,
    adminregister,
    childregister,
    caregiverregister,
    driverregister,
    userdashboard,
    admindashboard,
    dailyreport,
    classenrollment,
    payment,
    paymenthistory,
    paymentform,
    programs,
    programform,
    updateprogram,
    offeredprogram,
    newprogramoffer,
    offeredprogramdetail,
    addmenuschedule,
    extracurricular,
    extracurriculardetail,
    extracurricularform,
    activity,
    activityform,
    updateactivity,
    menu,
    menuform,
    updatemenu,
    room,
    roomform,
    childdailyreport,
    childlist,
    childreninclass,
    classroom,
    classenrollment,
    dailyreportform,
    paymentform,
    pickupschedule,
    programdata,
    shuttleserviceform,
    stafflist,
)

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('adminregister/', adminregister, name='adminregister'),
    path('childregister/', childregister, name='childregister'),
    path('caregiverregister/', caregiverregister, name='caregiverregister'),
    path('driverregister/', driverregister, name='driverregister'),
    path('userdashboard/', userdashboard, name="userdashboard"),
    path('admindashboard/', admindashboard, name='admindashboard'),
    path('dailyreport/', dailyreport, name='dailyreport'),
    path('classenrollment/', classenrollment, name='classenrollment'),
    path('payment/', payment, name='payment'),
    path('paymenthistory/', paymenthistory, name='paymenthistory'),
    path('programs/', programs, name='programs'),
    path('programform/', programform, name='programform'),
    path('updateprogram/', updateprogram, name='updateprogram'),
    path('offeredprogram/', offeredprogram, name='offeredprogram'),
    path('newprogramoffer/', newprogramoffer, name='newprogramoffer'),
    path('offeredprogramdetail/', offeredprogramdetail, name='offeredprogramdetail'),
    path('addmenuschedule/', addmenuschedule, name='addmenuschedule'),
    path('extracurricular/', extracurricular, name='extracurricular'),
    path('extracurriculardetail/', extracurriculardetail, name='extracurriculardetail'),
    path('extracurricularform/', extracurricularform, name='extracurricularform'),
    path('activity/', activity, name='activity'),
    path('activityform/', activityform, name='activityform'),
    path('updateactivity/', updateactivity, name='updateactivity'),
    path('menu/', menu, name='menu'),
    path('menuform/', menuform, name='menuform'),
    path('updatemenu/', updatemenu, name='updatemenu'),
    path('room/', room, name='room'),
    path('roomform/', roomform, name='roomform'),
    path('paymenthistory/', paymenthistory, name='paymenthistory'),
    path('paymentform/', paymentform, name='paymentform'),
     path('childdailyreport/', childdailyreport, name='childdailyreport'),
    path('childlist/', childlist, name='childlist'),
    path('childreninclass/', childreninclass, name='childreninclass'),
    path('classroom/', classroom, name='classroom'),
    path('classenrollment/', classenrollment, name='classenrollment'),
    path('dailyreportform/', dailyreportform, name='dailyreportform'),
    path('paymentform/', paymentform, name='paymentform'),
    path('pickupschedule/', pickupschedule, name='pickupschedule'),
    path('programdata/', programdata, name='programdata'),
    path('shuttleserviceform/', shuttleserviceform, name='shuttleserviceform'),
    path('stafflist/', stafflist, name='stafflist'),
]
